name: regada
channels:
    - defaults
    - pytorch
    - conda-forge
dependencies:
    - python=3.7.10
    - pytorch=1.11.0
    - numpy=1.21.2
    - cudatoolkit=11.3.1
    - scikit-learn=0.24.1
    - pandas=1.3.5
    - pip=23.3
    - scipy=1.7.3
    - tensorboard=2.11.2
    - torchvision=0.12.0
    - tqdm=4.66.1
    - einops=0.4.1
    - black=22.6.0
    - pip:
          - hydra-core==1.2
