# @package _global_

defaults:
    - override /dataset: howto100m

lr: 3e-5
save_metrics: [map-w, map-m, acc-a]

model:
    video_embedder:
        dropout: 0.3
    text_embedder:
        tokens: actadv
        main_modal: adv
        composition: emb
        dropout: 0.7
        layers_gated: 3
        layers_residual: 2

    loss_triplet_adverb: 2.0
    loss_triplet_action: 1.0
    loss_l2: 1.5